import Header from "./header";
import Script from "next/script";
import { ContextProvider } from "@/components/client/client";
export const metadata = {
  title: "Todo list",
  description: "Generated by create next app",
  link: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>
          <Header />
          {children}
          <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" />
        </ContextProvider>
      </body>
    </html>
  );
}
